#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install nginx -y

# Define the URL to redirect to
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Create a new configuration file for the redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 '$REDIRECT_URL';
    }
}
EOF'

# Remove the default symlink from sites-enabled (if exists)
sudo rm -f /etc/nginx/sites-enabled/default

# Use sed to create a symlink to enable the redirection configuration
sudo sed -i 's|#\?include /etc/nginx/sites-available/redirect_me;|include /etc/nginx/sites-available/redirect_me;|' /etc/nginx/nginx.conf

# Test the Nginx configuration to check for syntax errors
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
