#!/usr/bin/env bash
# script /redirect_me redirects to another page
# redirection 301 Permanently moved

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

url_red="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo sed -i "53i $url_red" /etc/nginx/sites-available/default
sudo service nginx restart
