#!/usr/bin/env bash
# only shows listening sockets

netstat -tlnp | awk 'NR>2 {print $1, $4, $7}' | while read proto local foreign pid_program
do
    pid=$(echo $pid_program | cut -d/ -f1)
    program=$(echo $pid_program | cut -d/ -f2-)
    if [ "$local" != "127.0.0.1:*" ] && [ "$local" != "localhost:*" ] && [ "$local" != "[::1]:*" ]
    then
        echo "$proto $local $foreign $program ($pid)"
    fi
done
