#!/usr/bin/env bash

# Script to display user information from /etc/passwd

file="/etc/passwd"

while IFS=":" read -r username passwd uid gid uinfo home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $uinfo"
done < "$file"
