#!/usr/bin/env bash
# sort apache log file
log_file="apache-access.log"

awk '{count[$1" "$9]++} END { for (key in count) { sub(/^[[:space:]]+/, "", key); print count[key], key } }' "$log_file" | sort -rn

