#!/usr/bin/env bash
# changes home ip address

# Get the container ID of the running Docker container
CONTAINER_ID=$(docker ps -q)

# Update the hosts file inside the Docker container
docker exec -it $CONTAINER_ID bash -c "echo '127.0.0.2 localhost' >> /etc/hosts"
docker exec -it $CONTAINER_ID bash -c "echo '8.8.8.8 facebook.com' >> /etc/hosts"

# Restart the networking service inside the Docker container
docker exec -it $CONTAINER_ID bash -c "service networking restart"
