#!/usr/bin/env bash
# changes home ip address

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

sudo service networking restart

if [ -f "/.dockerenv" ]; then
sudo service docker restart
fi
