#!/usr/bin/env bash
# changes home ip address

# Set localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Set facebook.com to resolve to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Restart the networking service
sudo systemctl restart networking.service
